import type { ITheme } from '@xterm/xterm'

export const TERMINAL_THEMES: Record<string, { name: string; theme: ITheme }> = {
  tokyoNight: {
    name: 'Tokyo Night',
    theme: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      cursorAccent: '#1a1b26',
      selectionBackground: '#33467c',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
  },
  dracula: {
    name: 'Dracula',
    theme: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      cursorAccent: '#282a36',
      selectionBackground: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  oneDark: {
    name: 'One Dark Pro',
    theme: {
      background: '#1e1e1e',
      foreground: '#abb2bf',
      cursor: '#528bff',
      cursorAccent: '#1e1e1e',
      selectionBackground: '#3e4451',
      black: '#282c34',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#5c6370',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
    },
  },
  cyberpunk: {
    name: 'Cyberpunk Neon',
    theme: {
      background: '#0d0e15',
      foreground: '#00ffcc',
      cursor: '#ff007f',
      cursorAccent: '#0d0e15',
      selectionBackground: '#ff007f44',
      black: '#10111a',
      red: '#ff3366',
      green: '#33ff99',
      yellow: '#ffe600',
      blue: '#00d0ff',
      magenta: '#ff00ff',
      cyan: '#00ffcc',
      white: '#ffffff',
      brightBlack: '#2a2b3d',
      brightRed: '#ff4d88',
      brightGreen: '#66ffb3',
      brightYellow: '#ffff33',
      brightBlue: '#33dcff',
      brightMagenta: '#ff33ff',
      brightCyan: '#33ffd6',
      brightWhite: '#ffffff',
    },
  }
}
